server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 121.41.112.246:8848

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

