server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  rabbitmq:
    host: 124.221.229.229
    port: 5672
    username: root
    password: root
  cloud:
    stream:
      binders:  # 在此处配置要绑定的rabbitmq的服务信息；
        #defaultRabbit 是RabbitMQ的一个代理实例名称，名字随便。要与下面的binder对应
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
      bindings: # 服务的整合处理
        #绑定的通道名称
        myChannel-in-0: # 这个名字是一个通道的名称
          #在RabbitMQ中是给交换机起名字
          destination: studyExchange # 表示要使用的Exchange名称定义
          contentType: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: groupA #添加组命

eureka:  # 客户端进行Eureka注册的配置
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: send-8803.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒)
    lease-renewal-interval-in-seconds: 2  # 设置心跳的时间间隔（默认是30秒）