server:
  port: 9527

spring:
  application:
    name: cloud-gateway
#############################新增网关配置###########################
  cloud:
    gateway:
      #不写discovery也可以实现动态路由？
      discovery:
        locator:
          enabled: true # 开启注册中心默认动态创建路由的过程。利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-provider-hystrix-payment #匹配后提供服务的路由地址
          #lb是指路由的一种通信协议，它实现了负载均衡通信功能
          predicates:
            - Path=/payment/hystrix/*/**      # 断言，路径相匹配的进行路由
            - After=2022-05-20T14:51:37.485+08:00[Asia/Shanghai]

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-provider-hystrix-payment #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**             # 断言，路径相匹配的进行路由
####################################################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
