server:
  port: 90

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#openFegin 3.0.1 版本设置
feign:
  client:
    config:
      default:
        #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
        connectTimeout: 5000
        #指的是建立连接后从服务器读取到可用资源所用的时间
        readTimeout: 5000
